name: CI Workflow
name: CI Workflow

on:
  push:
    branches:
      - dev
    branches:
      - dev

jobs:
  build-and-test:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

  handle-success-or-failure:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Handle success
        if: success()
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin main  # au cas où main n’est pas local
          git checkout main
          git merge --ff-only origin/dev
          git push https://x-access-token:${{ secrets.PAT_COURCI }}@github.com/LouisBrousse/courCI.git HEAD:main

      - name: Handle failure
        if: failure()
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout dev
          TIMESTAMP=$(date +%s)
          git branch failures/$TIMESTAMP
          git checkout failures/$TIMESTAMP
          git reset --hard HEAD@{1}
          git push https://x-access-token:${{ secrets.PAT_COURCI }}@github.com/LouisBrousse/courCI.git failures/$TIMESTAMP